import * as React from 'react';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import BottomNavigation from '@mui/material/BottomNavigation';
import BottomNavigationAction from '@mui/material/BottomNavigationAction';
import RestoreIcon from '@mui/icons-material/Restore';
import FavoriteIcon from '@mui/icons-material/Favorite';
import ArchiveIcon from '@mui/icons-material/Archive';
import Paper from '@mui/material/Paper';
import List from '@mui/material/List';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import Avatar from '@mui/material/Avatar';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { CardActionArea } from '@mui/material';
import Img1 from '../pictures/a.jpg';

const recentMessages = [
  {
    primary: 'Brunch this week?',
    secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/static/images/avatar/5.jpg',
  },
  {
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/static/images/avatar/3.jpg',
  },
];

const favoriteMessages = [
  {
    primary: 'Recipe to try',
    secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/static/images/avatar/2.jpg',
  },
];

const archiveMessages = [
  {
    primary: "Doctor's Appointment",
    secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/static/images/avatar/4.jpg',
  },
  {
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: '/static/images/avatar/5.jpg',
  },
];

const recentcards = [
  { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },
  // Add more card data objects as needed
  { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },  
  { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' }, 
   { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' }, 
    { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },
    { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },
];

const favcards = [
  { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },
  { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },
  { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },];
const archivecards = [
  { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },  
  { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },
  { title: ' Chorizo Paella', date: 'September 14, 2016', image: Img1, phone: '+123456789' },];

export default function FixedBottomNavigation() {
  const [value, setValue] = React.useState(0);
  const [messages, setMessages] = React.useState(recentMessages);
  const [cards, setCards] = React.useState(recentcards);

  const handleChange = (event, newValue) => {
    setValue(newValue);
    switch (newValue) {
      case 'recents':
        setMessages(recentMessages);
        setCards(recentcards);
        break;
      case 'favorites':
        setMessages(favoriteMessages);
        setCards(favcards);
        break;
      case 'archive':
        setMessages(archiveMessages);
        setCards(archivecards);
        break;
      default:
        break;
    }
  };

  return (
    <>
      <Box sx={{ pb: 7 }}>
        <CssBaseline />
        <Paper sx={{ left: 0, right: 0 }} elevation={3}>
          <BottomNavigation
            showLabels
            value={value}
            onChange={handleChange}
          >
            <BottomNavigationAction label="Recents" value="recents" icon={<RestoreIcon />} />
            <BottomNavigationAction label="Favorites" value="favorites" icon={<FavoriteIcon />} />
            <BottomNavigationAction label="Archive" value="archive" icon={<ArchiveIcon />} />
          </BottomNavigation>
        </Paper>
        <List>
          {messages.map(({ primary, secondary, person }, index) => (
            <ListItemButton key={index + person}>
              <ListItemAvatar>
                <Avatar alt="Profile Picture" src={person} />
              </ListItemAvatar>
              <ListItemText primary={primary} secondary={secondary} />
            </ListItemButton>
          ))}
        </List>
      </Box>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '100px', justifyContent: 'center' }}>
        {cards.map((card, index) => (
          <Card key={index} sx={{ maxWidth: 445 }}>
            <CardActionArea>
              <CardMedia
                component="img"
                height="140"
                image={card.image}
                alt="Card Image"
              />
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  {card.title}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {card.description}
                </Typography>
              </CardContent>
            </CardActionArea>
          </Card>
        ))}
      </div>
    </>
  );
}
